develop:
  dialect: mysql
  datasource: root:password@tcp(127.0.0.1:3306)/recipo?parseTime=true&collation=utf8_general_ci&interpolateParams=true&loc=Local
  dir: migration

production:
  dialect: mysql
  datasource: root:password@tcp(productiondb.com:3306)/recipo?parseTime=true&collation=utf8_general_ci&interpolateParams=true&loc=Local
  dir: migration
